from TheKeyMachine.tools.registry import ToolObject, load_tooltips
from TheKeyMachine.tools.onion_skin import controller, api


TOOLTIPS = load_tooltips(__file__)


class OnionSkinToolObject(ToolObject):
    ORDER = 710
    TOOLS = {
        "onion_skin": {
            "type": "check",
            "state_key": "onion_skin",
            "label": "Onion Skin",
            "icon": "onion_skin",
            "callback": api.toggle_window,
            "get_checked": api.is_window_open,
            "set_checked": api.toggle_window,
            "bind_checked_fn": api.bind_toolbar_button,
            "tooltip": TOOLTIPS["onion_skin"],
            "menu": {
                "label": "Onion Skin",
                "icon": "onion_skin",
                "items": [
                    {"type": "check", "command": "onion_skin_toggle"},
                    "separator",
                    {
                        "type": "menu",
                        "label": "Sampling",
                        "icon": "onion_skin",
                        "description": "Choose which nearby poses are ghosted and how densely they're sampled.",
                        "items": [
                            {"type": "check", "command": "onion_skin_neighbor_keys"},
                            {
                                "type": "choice",
                                "id": "onion_skin_frame_step",
                                "get_value": controller.get_relative_step,
                                "set_value": controller.set_relative_step,
                                "items": controller.frame_step_choices,
                            },
                            "separator",
                            {
                                "type": "dynamic_menu",
                                "label": "Nearby Frames",
                                "icon": "onion_skin",
                                "description": "Turn individual frames before and after the current one on or off.",
                                "builder": api.populate_nearby_frames_menu,
                            },
                            "separator",
                            {"type": "check", "command": "onion_skin_ghost_inbetweens"},
                            {
                                "type": "choice",
                                "id": "onion_skin_inbetween_count",
                                "get_value": controller.get_inbetween_count,
                                "set_value": controller.set_inbetween_count,
                                "items": controller.inbetween_count_choices,
                            },
                        ],
                    },
                    {
                        "type": "menu",
                        "label": "Appearance",
                        "icon": "onion_skin",
                        "description": "Set how ghosted poses are drawn: style, opacity, outline width, and color.",
                        "items": [
                            {"type": "section", "label": "Pose Style"},
                            {
                                "type": "choice",
                                "id": "onion_skin_display_style",
                                "get_value": controller.get_display_style,
                                "set_value": controller.set_display_style,
                                "items": controller.display_style_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Pose Opacity"},
                            {
                                "type": "choice",
                                "id": "onion_skin_opacity",
                                "get_value": controller.get_global_opacity,
                                "set_value": controller.set_global_opacity,
                                "items": controller.opacity_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Outline Width"},
                            {
                                "type": "choice",
                                "id": "onion_skin_outline_width",
                                "get_value": controller.get_outline_width,
                                "set_value": controller.set_outline_width,
                                "items": controller.outline_width_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Colors"},
                            "onion_skin_past_color",
                            "onion_skin_future_color",
                            "onion_skin_held_color",
                            "separator",
                            {"type": "check", "command": "onion_skin_draw_behind"},
                        ],
                    },
                    "separator",
                    {
                        "type": "menu",
                        "label": "Performance",
                        "icon": "refresh",
                        "description": "Balance how quickly ghosts catch up against viewport smoothness, and manage the onion buffer.",
                        "items": [
                            {"type": "check", "command": "onion_skin_auto_update"},
                            "separator",
                            {"type": "section", "label": "Update Speed"},
                            {
                                "type": "choice",
                                "id": "onion_skin_performance",
                                "get_value": api.get_performance,
                                "set_value": api.set_performance,
                                "items": api.performance_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Buffer Size"},
                            {
                                "type": "choice",
                                "id": "onion_skin_buffer_size",
                                "get_value": controller.get_max_buffer_size,
                                "set_value": controller.set_max_buffer_size,
                                "items": controller.buffer_size_choices,
                            },
                            "separator",
                            {"type": "check", "command": "onion_skin_auto_clear"},
                            "onion_skin_clear_buffer",
                        ],
                    },
                    "separator",
                    "onion_skin_add_selection",
                    "separator",
                    {"type": "check", "command": "onion_skin_stay_on_top"},
                ],
            },
        },
        "onion_skin_toggle": {
            "type": "check",
            "label": "Enable Onion Skin",
            "icon": "onion_skin_enable",
            "callback": controller.set_enabled,
            "get_checked": controller.is_enabled,
            "set_checked": controller.set_enabled,
            "tooltip": TOOLTIPS["toggle"],
        },
        "onion_skin_add_selection": {
            "type": "tool",
            "label": "Add Selected Objects",
            "icon": "add",
            "callback": controller.add_selected_objects,
            "tooltip": TOOLTIPS["add_selection"],
        },
        "onion_skin_clear_buffer": {
            "type": "tool",
            "label": "Clear Onion Buffer",
            "icon": "refresh",
            "callback": controller.clear_buffer,
            "tooltip": TOOLTIPS["clear_buffer"],
        },
        "onion_skin_draw_behind": {
            "type": "check",
            "label": "Draw Behind Current Pose",
            "icon": "onion_skin",
            "callback": controller.set_draw_behind,
            "get_checked": controller.is_draw_behind,
            "set_checked": controller.set_draw_behind,
            "tooltip": TOOLTIPS["draw_behind"],
        },
        "onion_skin_auto_clear": {
            "type": "check",
            "label": "Clear Buffer When Camera Moves",
            "icon": "refresh",
            "callback": controller.set_auto_clear_buffer,
            "get_checked": controller.is_auto_clear_buffer,
            "set_checked": controller.set_auto_clear_buffer,
            "tooltip": TOOLTIPS["auto_clear"],
        },
        "onion_skin_stay_on_top": {
            "type": "check",
            "label": "Stay On Top",
            "icon": "onion_skin",
            "callback": api.set_stay_on_top,
            "get_checked": api.is_stay_on_top,
            "set_checked": api.set_stay_on_top,
            "tooltip": TOOLTIPS["stay_on_top"],
        },
        "onion_skin_neighbor_keys": {
            "type": "check",
            "label": "Use Neighboring Key Poses",
            "icon": "onion_skin",
            "callback": controller.set_relative_to_keys,
            "get_checked": controller.is_relative_to_keys,
            "set_checked": controller.set_relative_to_keys,
            "tooltip": TOOLTIPS["neighbor_keys"],
        },
        "onion_skin_ghost_inbetweens": {
            "type": "check",
            "label": "Ghost In-Betweens",
            "icon": "onion_skin",
            "callback": controller.set_ghost_inbetweens,
            "get_checked": controller.is_ghost_inbetweens,
            "set_checked": controller.set_ghost_inbetweens,
            "tooltip": TOOLTIPS["ghost_inbetweens"],
        },
        "onion_skin_auto_update": {
            "type": "check",
            "label": "Auto Update",
            "icon": "refresh",
            "callback": api.set_auto_update,
            "get_checked": api.is_auto_update,
            "set_checked": api.set_auto_update,
            "tooltip": TOOLTIPS["auto_update"],
        },
        "onion_skin_past_color": {
            "type": "tool",
            "label": "Past Pose Color",
            "icon": "onion_skin",
            "callback": api.pick_past_color,
            "tooltip": TOOLTIPS["past_color"],
        },
        "onion_skin_future_color": {
            "type": "tool",
            "label": "Future Pose Color",
            "icon": "onion_skin",
            "callback": api.pick_future_color,
            "tooltip": TOOLTIPS["future_color"],
        },
        "onion_skin_held_color": {
            "type": "tool",
            "label": "Held Pose Color",
            "icon": "onion_skin",
            "callback": api.pick_held_color,
            "tooltip": TOOLTIPS["held_color"],
        },
    }
