from TheKeyMachine.core.Qt import QtCore  # type: ignore

from TheKeyMachine.tools.registry import ToolObject, load_tooltips
from TheKeyMachine.data.colors import COLORS
from TheKeyMachine.tools.tracer import api

TOOLTIPS = load_tooltips(__file__)


class TracerToolObject(ToolObject):
    ORDER = 700
    TOOLS = {
        "create_tracer": {
            "type": "check",
            "label": "Tracer",
            "icon": "tracer",
            "state_key": "create_tracer",
            "callback": api.set_tracer_enabled,
            "get_checked": api.has_any_tracer,
            "set_checked": api.set_tracer_enabled,
            "tooltip": TOOLTIPS["create"],
            "operation": {
                "undo": True,
                "suspend_refresh": True,
                "rollback_on_cancel": True,
                "capture_animation_context": True,
            },
            "menu": {
                "label": "Tracer",
                "icon": "tracer",
                "items": [
                    {"type": "check", "command": "tracer_connected"},
                    "separator",
                    "tracer_create_another",
                    "tracer_remove",
                    "tracer_set_range",
                    "separator",
                    {
                        "type": "dynamic_menu",
                        "label": "Offset",
                        "icon": "tracer_select_offset",
                        "builder": api.populate_tracer_offsets_menu,
                    },
                    "separator",
                    {
                        "type": "menu",
                        "label": "Style",
                        "icon": "tracer",
                        "items": [
                            {
                                "type": "choice",
                                "id": "tracer_style",
                                "get_value": api.get_tracer_style,
                                "set_value": api.apply_tracer_style,
                                "items": api.tracer_style_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Size"},
                            {
                                "type": "choice",
                                "id": "tracer_size",
                                "get_value": api.get_tracer_size,
                                "set_value": api.set_tracer_size,
                                "items": api.tracer_size_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Color"},
                            "tracer_grey",
                            "tracer_red",
                            "tracer_blue",
                        ],
                    },
                    {
                        "type": "menu",
                        "label": "Frames Before and After",
                        "icon": "tracer",
                        "items": [
                            {
                                "type": "choice",
                                "id": "tracer_range",
                                "get_value": api.get_tracer_range,
                                "set_value": api.set_tracer_range,
                                "items": api.tracer_range_choices,
                            },
                            "separator",
                            {"type": "section", "label": "Direction"},
                            {
                                "type": "choice",
                                "id": "tracer_direction",
                                "get_value": api.get_tracer_direction,
                                "set_value": api.set_tracer_direction,
                                "items": api.tracer_direction_choices,
                            },
                        ],
                    },
                    {"type": "check", "command": "tracer_falloff"},
                    "separator",
                    "tracer_camera_space",
                    "tracer_relative_space",
                    "separator",
                    {
                        "type": "menu",
                        "label": "More",
                        "icon": "tracer",
                        "items": [
                            "tracer_refresh",
                            "tracer_show_hide",
                            "tracer_world_space",
                            {"type": "check", "command": "tracer_xray"},
                            "separator",
                            {"type": "section", "label": "Performance"},
                            {
                                "type": "choice",
                                "id": "tracer_performance",
                                "get_value": api.get_performance,
                                "set_value": api.set_performance,
                                "items": api.performance_choices,
                            },
                        ],
                    },
                ],
            },
        },
        "tracer_create_another": {
            "type": "tool",
            "label": "Create Tracer",
            "icon": "tracer",
            "callback": api.create_additional_tracer,
            "tooltip": TOOLTIPS["create_another"],
            "operation": {
                "suspend_refresh": True,
                "rollback_on_cancel": True,
                "capture_animation_context": True,
            },
        },
        "tracer_set_range": {
            "type": "tool",
            "label": "Set Range",
            "icon": "tracer",
            "callback": api.set_tracer_playback_range,
            "tooltip": TOOLTIPS["set_range"],
        },
        "tracer_refresh": {
            "type": "tool",
            "label": "Force Refresh",
            "icon": "tracer_refresh",
            "callback": api.refresh_tracer,
            "tooltip": TOOLTIPS["refresh"],
        },
        "tracer_show_hide": {
            "type": "tool",
            "label": "Toggle Tracer",
            "icon": "tracer_show_hide",
            "callback": api.toggle_tracer,
            "tooltip": TOOLTIPS["toggle"],
        },
        "tracer_offset_node": {
            "type": "tool",
            "label": "Select Offset Object",
            "icon": "tracer_select_offset",
            "callback": api.select_tracer_offset_node,
            "tooltip": TOOLTIPS["offset"],
        },
        "tracer_world_space": {
            "type": "tool",
            "label": "World Space",
            "icon": "tracer",
            "callback": api.set_world_space,
            "tooltip": TOOLTIPS["world_space"],
            "operation": {"suspend_refresh": True, "rollback_on_cancel": True},
        },
        "tracer_camera_space": {
            "type": "tool",
            "label": "Camera Space",
            "icon": "tracer",
            "callback": api.set_camera_space,
            "tooltip": TOOLTIPS["camera_space"],
            "operation": {"suspend_refresh": True, "rollback_on_cancel": True},
        },
        "tracer_relative_space": {
            "type": "tool",
            "label": "Relative Space",
            "icon": "tracer",
            "callback": api.set_relative_space,
            "tooltip": TOOLTIPS["relative_space"],
            "operation": {"suspend_refresh": True, "rollback_on_cancel": True},
        },
        "tracer_grey": {
            "type": "tool",
            "label": "Tracer Color: Grey",
            "icon": "tracer_grey",
            "callback": api.set_tracer_grey_color,
            "tooltip": TOOLTIPS["grey"],
        },
        "tracer_red": {
            "type": "tool",
            "label": "Tracer Color: Red",
            "icon": "tracer_red",
            "callback": api.set_tracer_red_color,
            "tooltip": TOOLTIPS["red"],
        },
        "tracer_blue": {
            "type": "tool",
            "label": "Tracer Color: Blue",
            "icon": "tracer_blue",
            "callback": api.set_tracer_blue_color,
            "tooltip": TOOLTIPS["blue"],
        },
        "tracer_remove": {
            "type": "tool",
            "label": "Remove Tracer",
            "icon": "tracer_remove",
            "callback": api.remove_tracer,
            "tooltip": TOOLTIPS["remove"],
        },
        "tracer_style_cycle": {
            "type": "tool",
            "label": "Cycle Tracer Style",
            "icon": "tracer",
            "callback": api.cycle_tracer_style,
            "tooltip": TOOLTIPS["cycle_style"],
        },
        "tracer_range_cycle": {
            "type": "tool",
            "label": "Cycle Tracer Range",
            "icon": "tracer",
            "callback": api.cycle_tracer_range,
            "tooltip": TOOLTIPS["cycle_range"],
        },
        "tracer_performance_cycle": {
            "type": "tool",
            "label": "Cycle Tracer Performance",
            "icon": "tracer_refresh",
            "callback": api.cycle_performance,
            "tooltip": TOOLTIPS["cycle_performance"],
        },
        "tracer_falloff": {
            "type": "check",
            "label": "Transparency Falloff",
            "icon": "tracer",
            "callback": api.set_transparency_falloff,
            "get_checked": api.has_transparency_falloff,
            "set_checked": api.set_transparency_falloff,
            "tooltip": TOOLTIPS["falloff"],
        },
        "tracer_xray": {
            "type": "check",
            "label": "X-Ray Tracer",
            "icon": "tracer",
            "callback": api.set_xray,
            "get_checked": api.is_xray_enabled,
            "set_checked": api.set_xray,
            "tooltip": TOOLTIPS["xray"],
        },
        "tracer_connected": {
            "type": "check",
            "label": "Auto Update",
            "icon": "tracer",
            "callback": api.set_connected,
            "get_checked": api.is_connected,
            "set_checked": api.set_connected,
            "tooltip": TOOLTIPS["connected"],
        },
    }
    SECTION = {
        "id": "tracer_tools",
        "i18n_key": "create_tracer",
        "label": "Tracer",
        "color": COLORS.toolbar.red.hex,
        "items": [
            {
                "id": "create_tracer",
                "shortcuts": [
                    {"id": "tracer_refresh", "keys": [QtCore.Qt.Key_Control]},
                    {"id": "tracer_create_another", "keys": [QtCore.Qt.Key_Shift]},
                    {"id": "tracer_offset_node", "keys": [QtCore.Qt.Key_Alt]},
                    {
                        "id": "tracer_show_hide",
                        "keys": [QtCore.Qt.Key_Control, QtCore.Qt.Key_Shift],
                    },
                    {
                        "id": "tracer_style_cycle",
                        "keys": [QtCore.Qt.Key_Shift, QtCore.Qt.Key_Alt],
                    },
                    {
                        "id": "tracer_remove",
                        "keys": [QtCore.Qt.Key_Control, QtCore.Qt.Key_Alt],
                    },
                    {
                        "id": "tracer_range_cycle",
                        "keys": [
                            QtCore.Qt.Key_Control,
                            QtCore.Qt.Key_Shift,
                            QtCore.Qt.Key_Alt,
                        ],
                    },
                ],
            },
            {"id": "tracer_connected"},
            "separator",
            {"id": "tracer_refresh"},
            {"id": "tracer_show_hide"},
            {"id": "tracer_offset_node"},
            "separator",
            {"id": "tracer_grey"},
            {"id": "tracer_red"},
            {"id": "tracer_blue"},
            "separator",
            {"id": "tracer_remove"},
        ],
    }
