from functools import partial

from TheKeyMachine.tools.registry import ToolObject, load_tooltips
from TheKeyMachine.tools.tkm_menu import api

TOOLTIPS = load_tooltips(__file__)


class TkmMenuToolObject(ToolObject):
    ORDER = 10
    TOOLS = {
        "TKM": {
            "type": "menu",
            "label": "TheKeyMachine",
            "icon": "tkm_main",
            "tooltip": TOOLTIPS["menu"],
            "callback": api.show_menu,
            "menu": {
                "label": "TheKeyMachine",
                "description": TOOLTIPS["menu"][0],
                "items": [
                    {"type": "widget", "factory": api.create_logo_action},
                    {
                        "type": "menu",
                        "command": "main_preferences_menu",
                        "label": "Preferences",
                        "icon": "settings",
                        "description": TOOLTIPS["preferences"][0],
                        "items": [
                            "toolbar_add_shelf_button",
                            {"type": "check", "command": "start_with_maya"},
                            {"type": "check", "command": "show_tooltips"},
                            "separator",
                            {
                                "type": "section",
                                "label": "Alignment",
                                "i18n_key": "alignment_section",
                            },
                            {
                                "type": "choice",
                                "id": "toolbar_icon_alignment",
                                "get_value": api.get_alignment,
                                "set_value": api.set_alignment,
                                "items": api.alignment_choices,
                            },
                        ],
                    },
                    "hotkeys_window",
                    "workspaces_window",
                    {
                        "type": "menu",
                        "command": "main_dock_menu",
                        "label": "Dock",
                        "icon": "dock",
                        "description": TOOLTIPS["dock"][0],
                        "items": [
                            {
                                "type": "section",
                                "label": "Position",
                                "i18n_key": "position_section",
                            },
                            {
                                "type": "choice",
                                "id": "dock_orientation",
                                "setting_label": "Dock Position",
                                "get_value": api.get_dock_orientation,
                                "set_value": api.set_dock_orientation,
                                "items": api.dock_orientation_choices,
                            },
                            "separator",
                            {
                                "type": "section",
                                "label": "Dock Area",
                                "i18n_key": "dock_area_section",
                            },
                            {
                                "type": "choice",
                                "id": "dock_layout",
                                "setting_label": "Dock Area",
                                "get_value": api.get_dock_layout,
                                "set_value": api.set_dock_layout,
                                "items": api.dock_layout_choices,
                            },
                        ],
                    },
                    {
                        "type": "menu",
                        "command": "main_system_menu",
                        "label": "System",
                        "icon": "system",
                        "description": TOOLTIPS["system"][0],
                        "items": [
                            "toolbar_reload",
                            "toolbar_unload",
                            "toolbar_uninstall",
                            {
                                "type": "dynamic_menu",
                                "command": "languages_menu",
                                "label": "Languages",
                                "icon": "languages",
                                "description": TOOLTIPS["languages"][0],
                                "separator_before": True,
                                "builder": api.populate_languages_menu,
                            },
                        ],
                    },
                    "separator",
                    {
                        "type": "menu",
                        "command": "help_menu",
                        "label": "Help",
                        "icon": "help",
                        "description": TOOLTIPS["help"][0],
                        "items": [
                            {
                                "type": "dynamic_menu",
                                "command": "bug_report_window",
                                "label": "Bug Report",
                                "icon": "bug",
                                "description": TOOLTIPS["bug_report"][0],
                                "available": api.bug_reports_available,
                                "builder": api.populate_bug_report_menu,
                            },
                            "separator",
                            {
                                "label": "Documentation",
                                "icon": "help",
                                "description": "Open TheKeyMachine documentation.",
                                "i18n_key": "documentation",
                                "callback": partial(
                                    api.open_url,
                                    "https://thekeymachine.gitbook.io/base",
                                ),
                            },
                            {
                                "label": "GitHub",
                                "icon": "github",
                                "description": "Open the TheKeyMachine project on GitHub.",
                                "i18n_key": "github",
                                "callback": partial(
                                    api.open_url, "https://github.com/Alehaaaa/TKM"
                                ),
                            },
                            {
                                "label": "Discord",
                                "icon": "discord",
                                "description": "Open the TheKeyMachine Discord community.",
                                "i18n_key": "discord",
                                "callback": partial(
                                    api.open_url, "https://discord.gg/G2J5yyjz"
                                ),
                            },
                            {
                                "label": "YouTube",
                                "icon": "youtube",
                                "description": "Open TheKeyMachine tutorials on YouTube.",
                                "i18n_key": "youtube",
                                "callback": partial(
                                    api.open_url,
                                    "https://www.youtube.com/@TheKeyMachineAnimationTools",
                                ),
                            },
                        ],
                    },
                    "donate_window",
                    "check_for_updates",
                    "about_window",
                    {
                        "type": "dynamic_menu",
                        "label": "Debug",
                        "i18n_key": "debug_menu",
                        "icon": "bug",
                        "description": "Developer-only diagnostics and test actions.",
                        "available": api.tool_debug_enabled,
                        "separator_before": True,
                        "builder": api.rebuild_debug_menu,
                    },
                ],
            },
        },
        "toolbar_toggle": {
            "type": "tool",
            "label": "Toggle Toolbar",
            "icon": "tkm_main",
            "callback": api.toggle_toolbar,
            "tooltip": TOOLTIPS["toggle"],
        },
        "toolbar_add_shelf_button": {
            "type": "tool",
            "label": "Add Toggle Button To Shelf",
            "icon": "tkm_main",
            "callback": api.add_shelf_button,
            "tooltip": TOOLTIPS["shelf"],
        },
        "toolbar_reload": {
            "type": "tool",
            "label": "Reload",
            "icon": "reload",
            "callback": api.reload_toolbar,
            "tooltip": TOOLTIPS["reload"],
        },
        "toolbar_unload": {
            "type": "tool",
            "label": "Unload",
            "icon": "close",
            "callback": api.unload_toolbar,
            "tooltip": TOOLTIPS["unload"],
        },
        "toolbar_uninstall": {
            "type": "tool",
            "label": "Uninstall",
            "icon": "remove",
            "callback": api.uninstall,
            "tooltip": TOOLTIPS["uninstall"],
        },
        "check_for_updates": {
            "type": "tool",
            "label": "Check for Updates",
            "icon": "check_updates",
            "callback": api.check_for_updates,
            "available": api.updates_available,
            "tooltip": TOOLTIPS["updates"],
            "operation": {
                "progress": False,
                "undo": False,
                "suspend_refresh": False,
                "show_success_message": False,
            },
        },
        "install_update": {
            "type": "tool",
            "label": "Install Update",
            "icon": "check_updates",
            "callback": api.install_update,
            "pinnable": False,
            "operation": {
                "undo": False,
                "suspend_refresh": False,
                "show_success_message": False,
            },
        },
        "main_preferences_menu": {
            "type": "menu",
            "label": "Preferences",
            "icon": "settings",
            "callback": partial(api.show_menu, "main_preferences_menu"),
            "tooltip": TOOLTIPS["preferences"],
        },
        "start_with_maya": {
            "type": "check",
            "label": "Start with Maya",
            "callback": api.set_start_with_maya,
            "get_checked": api.starts_with_maya,
            "set_checked": api.set_start_with_maya,
            "tooltip": TOOLTIPS["startup"],
        },
        "show_tooltips": {
            "type": "check",
            "label": "Show Tooltips",
            "callback": api.set_tooltips_enabled,
            "get_checked": api.tooltips_enabled,
            "set_checked": api.set_tooltips_enabled,
            "tooltip": TOOLTIPS["tooltips"],
        },
        "main_dock_menu": {
            "type": "menu",
            "label": "Dock",
            "icon": "dock",
            "callback": partial(api.show_menu, "main_dock_menu"),
            "tooltip": TOOLTIPS["dock"],
        },
        "main_system_menu": {
            "type": "menu",
            "label": "System",
            "icon": "system",
            "callback": partial(api.show_menu, "main_system_menu"),
            "tooltip": TOOLTIPS["system"],
        },
        "languages_menu": {
            "type": "menu",
            "label": "Languages",
            "icon": "globe",
            "callback": partial(api.show_menu, "languages_menu"),
            "tooltip": TOOLTIPS["languages"],
        },
        "help_menu": {
            "type": "menu",
            "label": "Help",
            "icon": "help",
            "callback": partial(api.show_menu, "help_menu"),
            "tooltip": TOOLTIPS["help"],
        },
        "hotkeys_window": {
            "type": "tool",
            "label": "Hotkeys",
            "icon": "hotkeys",
            "callback": api.show_hotkeys,
            "tooltip": TOOLTIPS["hotkeys"],
        },
        "workspaces_window": {
            "type": "tool",
            "label": "Workspaces",
            "icon": "align",
            "callback": api.show_workspaces,
            "tooltip": TOOLTIPS["workspaces"],
        },
        "version_history_window": {
            "type": "tool",
            "label": "Version History",
            "icon": "about",
            "callback": api.show_version_history,
            "tooltip": TOOLTIPS["history"],
        },
        "about_window": {
            "type": "tool",
            "label": "About",
            "icon": "about",
            "callback": api.show_about,
            "tooltip": TOOLTIPS["about"],
        },
        "donate_window": {
            "type": "tool",
            "label": "Donate",
            "icon": "donate",
            "callback": api.show_donate,
            "tooltip": TOOLTIPS["donate"],
        },
        "bug_report_window": {
            "type": "menu",
            "label": "Bug Report",
            "icon": "bug",
            "callback": partial(api.show_menu, "bug_report_window"),
            "available": api.bug_reports_available,
            "tooltip": TOOLTIPS["bug_report"],
            "menu": api.populate_bug_report_menu,
        },
        "bug_report_open_dialog": {
            "type": "tool",
            "label": "Report a Bug",
            "icon": "bug",
            "callback": api.show_bug_report,
            "tooltip": TOOLTIPS["bug_report"],
        },
    }
    SECTION = {
        "id": "system",
        "label": "TKM Menu",
        "icon": "tkm_main",
        "hiddeable": False,
        "items": [
            *(
                {"id": tool_id}
                for tool_id in (
                    "main_preferences_menu",
                    "main_dock_menu",
                    "main_system_menu",
                    "help_menu",
                    "toolbar_toggle",
                    "toolbar_add_shelf_button",
                    "toolbar_reload",
                    "toolbar_unload",
                    "toolbar_uninstall",
                    "check_for_updates",
                    "hotkeys_window",
                    "version_history_window",
                    "about_window",
                    "donate_window",
                    "bug_report_window",
                )
            ),
        ],
    }
